### ISSUE TITLE
How to compute Slist Mlist Glist

### ISSUE THREAD

**Issue by yaoxt3** [1am5hy/EducationProject#1]
Hi, thank you for releasing this project. I found that there are some parameters such as Slist, Mlist and Glist defined in the code, how do you obtain these parameters? If I replace panda model with kuka model, how can I calculate the Slist, Mlist and Glist. Thank you.

**Comment by 1am5hy** [comment]
Hi! The kinematics of the robot defined here uses the the concept of screw axes. Slist means the screw list, Mlist means the configuration of manipulator link i relative to link i-1 when the manipulator is at its zero position, and Glist is inertia matrix of a given link. You would first have to hand calculate each of these parameters. 

This code is simply a test code I used to understand kinematics. It is derived from a textbook called Modern Robotics, by Kevin M. Lynch. There is also a code library based around this textbook on Github!

I hope this helps you, and have fun with Robotics!

**Comment by yaoxt3** [comment]
Thanks a lot! Have a nice day.
